let mapleader = ","
let maplocalleader = ","

set noexrc
set secure

packadd chezmoi.vim

if &compatible
  set nocompatible
endif

source ~/.config/nvim/core/misc.vim
source ~/.config/nvim/core/cursor.vim
source ~/.config/nvim/core/spell.vim
source ~/.config/nvim/core/colour.vim
source ~/.config/nvim/core/clipboard.vim
source ~/.config/nvim/core/buffer.vim
source ~/.config/nvim/core/window.vim

{{ if eq .vim_flag "good" -}}
source ~/.config/nvim/core/plug.vim
source ~/.config/nvim/core/gruvbox-material.vim
source ~/.config/nvim/core/theme.vim
" Strict loading order: 'plug.vim' -> 'gruvbox.vim' -> 'theme.vim'
{{ end -}}
